In [1]:
import pandas as pd

In [4]:
df = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

In [7]:
type(df)

list

In [13]:
df1=df[0]

In [14]:
df1.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [16]:
df1.dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

In [17]:
df1.head(3)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537

In [18]:
df1.tail(3)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [24]:
df1[['Age','GS']]

    Age  GS
0    24  22
1    20   0
2    21  67
3    28   0
4    29  72
..   ..  ..
670  26  68
671  26  48
672  26  20
673  22  45
674  25  59

[675 rows x 2 columns]

In [25]:
df1.to_csv("nba.csv")

In [39]:
cricInfo=pd.read_html("https://stats.espncricinfo.com/ci/engine/records/averages/batting.html?class=3;id=6;type=team")

In [40]:
len(cricInfo)

3

In [47]:
playerStats = cricInfo[0]

In [45]:
cricInfo[1]

                                                   0
0  By default, the shading indicates records from...
1  Adjust:  most recent  | past week  | past mont...

In [46]:
cricInfo[2]

                                                   0
0  Records includes the following current or rece...
1  India v Sri Lanka at Dharamsala, 2nd T20I, Feb...
2  India v Sri Lanka at Lucknow, 1st T20I, Feb 24...
3  India v West Indies at Kolkata, 3rd T20I, Feb ...

In [48]:
playerStats

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,AB Agarkar,2006-2007,4,2,0,15,14,7.50,11,136.36,0,0,0,2,0
1,KK Ahmed,2018-2019,14,1,1,1,1*,-,1,100.00,0,0,0,0,0
2,S Aravind,2015-2015,1,-,-,-,-,-,-,-,-,-,-,-,-
3,R Ashwin,2010-2021,51,11,7,123,31*,30.75,115,106.95,0,0,0,14,1
4,Avesh Khan,2022-2022,1,-,-,-,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,R Vinay Kumar,2010-2013,9,1,1,2,2*,-,4,50.00,0,0,0,0,0
93,Washington Sundar,2017-2021,31,11,4,47,14*,6.71,32,146.87,0,0,3,4,3
94,SA Yadav,2021-2022,14,12,3,351,65,39.00,212,165.56,0,4,1,32,20
95,UT Yadav,2012-2019,7,1,0,2,2,2.00,4,50.00,0,0,0,0,0
96,Yuvraj Singh,2007-2017,58,51,9,1177,77*,28.02,863,136.38,0,8,1,77,74

In [53]:
import json

In [76]:
d = '''
{
    "name" : "Vaibhav Yaramwar",
    "emailid" : "vaibhav.yaramwar@gmail.com",
    "tech" : ["AI","ML","DL"],
    "platform" : ["ineuron","kidsneuron","oneneuron"]
}
'''

In [77]:
d1 = json.loads(d)

In [78]:
type(d1)

dict

In [81]:
pd.DataFrame(d1)

               name                     emailid tech    platform
0  Vaibhav Yaramwar  vaibhav.yaramwar@gmail.com   AI     ineuron
1  Vaibhav Yaramwar  vaibhav.yaramwar@gmail.com   ML  kidsneuron
2  Vaibhav Yaramwar  vaibhav.yaramwar@gmail.com   DL   oneneuron

In [86]:
d = '''
{"packetType":"D","data":{"checkEngineLightFlag":"F","batteryVoltageStableTime":0,"batteryVoltageStable":"0","batteryVoltageOff":"12.42","batteryCrankParamTN":"-0.08","batteryCrankParamVN":"0.00","batteryCrankParamTP":"-0.08","batteryCrankParamVP":"0.00","batteryCrankParamTT":"-0.00008","batteryCrankParamV0":"0.00","batteryVoltageMaxOn":"13.05","batteryVoltageMinOn":"12.97","batteryVoltageMaxOff":"12.46","batteryVoltageMinOff":"12.36","batteryVoltageOnAverage":"13.02","engineLoadMax":"84","engineLoadAverage":"39.98","rpmMax":"3487","rpmAverage":"1431.29","gpsSpeedAverage":"21.99","vssMax":"53.44","vssAverage":"23.06","tcuTemperatureMin":"82.40","tcuTemperatureMax":"109.40","tcuTemperatureAverage":"104.87","coolantMin":"158.00","coolantMax":"188.60","coolantAverage":"180.20","packetStartLocal":1508143346000,"tripStartLocal":1508143346000,"milIndicator":"F","monitorsNotReady":0,"imei":"60DF5417","gatewayTs":1515613306592,"diagnosticTroubleCodeData":[],"diagnosticPidData":[[64768,47,100],[64768,1,517376],[64800,1,262144],[64768,5,125]]},"header":{"iwrapVer":"1.9.20","sourceSystem":"CDP","configVer":"1.1","oemName":"HUM","unitType":0,"cpVer":"7.50.1.9","igpsVer":"1.3.7","messageType":"Notification","pomVer":"1.0","headerVer":"V6","timestamp":0,"deviceType":"InDrive","visorVer":"1.4.35","transactionId":"53098471-7787-4160-94b3-cd69dcc70416","deviceSerialNo":"60DF5417","subOrganization":"HUM","organization":"HUM","imei":"60DF5417","operation":"Notification"}}
'''

In [87]:
d2 = json.loads(d)

In [88]:
type(d2)

dict

In [89]:
d2

{'packetType': 'D',
 'data': {'checkEngineLightFlag': 'F',
  'batteryVoltageStableTime': 0,
  'batteryVoltageStable': '0',
  'batteryVoltageOff': '12.42',
  'batteryCrankParamTN': '-0.08',
  'batteryCrankParamVN': '0.00',
  'batteryCrankParamTP': '-0.08',
  'batteryCrankParamVP': '0.00',
  'batteryCrankParamTT': '-0.00008',
  'batteryCrankParamV0': '0.00',
  'batteryVoltageMaxOn': '13.05',
  'batteryVoltageMinOn': '12.97',
  'batteryVoltageMaxOff': '12.46',
  'batteryVoltageMinOff': '12.36',
  'batteryVoltageOnAverage': '13.02',
  'engineLoadMax': '84',
  'engineLoadAverage': '39.98',
  'rpmMax': '3487',
  'rpmAverage': '1431.29',
  'gpsSpeedAverage': '21.99',
  'vssMax': '53.44',
  'vssAverage': '23.06',
  'tcuTemperatureMin': '82.40',
  'tcuTemperatureMax': '109.40',
  'tcuTemperatureAverage': '104.87',
  'coolantMin': '158.00',
  'coolantMax': '188.60',
  'coolantAverage': '180.20',
  'packetStartLocal': 1508143346000,
  'tripStartLocal': 1508143346000,
  'milIndicator': 'F',
  'monitorsNotReady': 0,
  'imei': '60DF5417',
  'gatewayTs': 1515613306592,
  'diagnosticTroubleCodeData': [],
  'diagnosticPidData': [[64768, 47, 100],
   [64768, 1, 517376],
   [64800, 1, 262144],
   [64768, 5, 125]]},
 'header': {'iwrapVer': '1.9.20',
  'sourceSystem': 'CDP',
  'configVer': '1.1',
  'oemName': 'HUM',
  'unitType': 0,
  'cpVer': '7.50.1.9',
  'igpsVer': '1.3.7',
  'messageType': 'Notification',
  'pomVer': '1.0',
  'headerVer': 'V6',
  'timestamp': 0,
  'deviceType': 'InDrive',
  'visorVer': '1.4.35',
  'transactionId': '53098471-7787-4160-94b3-cd69dcc70416',
  'deviceSerialNo': '60DF5417',
  'subOrganization': 'HUM',
  'organization': 'HUM',
  'imei': '60DF5417',
  'operation': 'Notification'}}

In [94]:
del d2['data']["diagnosticTroubleCodeData"]

In [95]:
d2

{'packetType': 'D',
 'data': {'checkEngineLightFlag': 'F',
  'batteryVoltageStableTime': 0,
  'batteryVoltageStable': '0',
  'batteryVoltageOff': '12.42',
  'batteryCrankParamTN': '-0.08',
  'batteryCrankParamVN': '0.00',
  'batteryCrankParamTP': '-0.08',
  'batteryCrankParamVP': '0.00',
  'batteryCrankParamTT': '-0.00008',
  'batteryCrankParamV0': '0.00',
  'batteryVoltageMaxOn': '13.05',
  'batteryVoltageMinOn': '12.97',
  'batteryVoltageMaxOff': '12.46',
  'batteryVoltageMinOff': '12.36',
  'batteryVoltageOnAverage': '13.02',
  'engineLoadMax': '84',
  'engineLoadAverage': '39.98',
  'rpmMax': '3487',
  'rpmAverage': '1431.29',
  'gpsSpeedAverage': '21.99',
  'vssMax': '53.44',
  'vssAverage': '23.06',
  'tcuTemperatureMin': '82.40',
  'tcuTemperatureMax': '109.40',
  'tcuTemperatureAverage': '104.87',
  'coolantMin': '158.00',
  'coolantMax': '188.60',
  'coolantAverage': '180.20',
  'packetStartLocal': 1508143346000,
  'tripStartLocal': 1508143346000,
  'milIndicator': 'F',
  'monitorsNotReady': 0,
  'imei': '60DF5417',
  'gatewayTs': 1515613306592,
  'diagnosticPidData': [[64768, 47, 100],
   [64768, 1, 517376],
   [64800, 1, 262144],
   [64768, 5, 125]]},
 'header': {'iwrapVer': '1.9.20',
  'sourceSystem': 'CDP',
  'configVer': '1.1',
  'oemName': 'HUM',
  'unitType': 0,
  'cpVer': '7.50.1.9',
  'igpsVer': '1.3.7',
  'messageType': 'Notification',
  'pomVer': '1.0',
  'headerVer': 'V6',
  'timestamp': 0,
  'deviceType': 'InDrive',
  'visorVer': '1.4.35',
  'transactionId': '53098471-7787-4160-94b3-cd69dcc70416',
  'deviceSerialNo': '60DF5417',
  'subOrganization': 'HUM',
  'organization': 'HUM',
  'imei': '60DF5417',
  'operation': 'Notification'}}

In [97]:
pd.DataFrame(d2)

,packetType,data,header
checkEngineLightFlag,D,F,NaN
batteryVoltageStableTime,D,0,NaN
batteryVoltageStable,D,0,NaN
batteryVoltageOff,D,12.42,NaN
batteryCrankParamTN,D,-0.08,NaN
batteryCrankParamVN,D,0.00,NaN
batteryCrankParamTP,D,-0.08,NaN
batteryCrankParamVP,D,0.00,NaN
batteryCrankParamTT,D,-0.00008,NaN
batteryCrankParamV0,D,0.00,NaN
batteryVoltageMaxOn,D,13.05,NaN
batteryVoltageMinOn,D,12.97,NaN
batteryVoltageMaxOff,D,12.46,NaN
batteryVoltageMinOff,D,12.36,NaN
batteryVoltageOnAverage,D,13.02,NaN
engineLoadMax,D,84,NaN
engineLoadAverage,D,39.98,NaN
rpmMax,D,3487,NaN
rpmAverage,D,1431.29,NaN
gpsSpeedAverage,D,21.99,NaN
vssMax,D,53.44,NaN
vssAverage,D,23.06,NaN
tcuTemperatureMin,D,82.40,NaN
tcuTemperatureMax,D,109.40,NaN
tcuTemperatureAverage,D,104.87,NaN
coolantMin,D,158.00,NaN
coolantMax,D,188.60,NaN
coolantAverage,D,180.20,NaN
packetStartLocal,D,1508143346000,NaN
tripStartLocal,D,1508143346000,NaN
milIndicator,D,F,NaN
monitorsNotReady,D,0,NaN
imei,D,60DF5417,60DF5417
gatewayTs,D,1515613306592,NaN
diagnosticPidData,D,"[[64768, 47, 100], [64768, 1, 517376], [64800,...",NaN
iwrapVer,D,NaN,1.9.20
sourceSystem,D,NaN,CDP
configVer,D,NaN,1.1
oemName,D,NaN,HUM
unitType,D,NaN,0
cpVer,D,NaN,7.50.1.9
igpsVer,D,NaN,1.3.7
messageType,D,NaN,Notification
pomVer,D,NaN,1.0
headerVer,D,NaN,V6
timestamp,D,NaN,0
deviceType,D,NaN,InDrive
visorVer,D,NaN,1.4.35
transactionId,D,NaN,53098471-7787-4160-94b3-cd69dcc70416
deviceSerialNo,D,NaN,60DF5417
subOrganization,D,NaN,HUM
organization,D,NaN,HUM
operation,D,NaN,Notification

In [99]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
df3=pd.read_json(url)

In [100]:
df3.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'draft', 'pull_request', 'body', 'reactions',
       'timeline_url', 'performed_via_github_app'],
      dtype='object')

In [103]:
nestdict=df3['user']

In [109]:
str(nestdict)

"0     {'login': 'mroeschke', 'id': 10647082, 'node_i...\n1     {'login': 'lukemanley', 'id': 8519523, 'node_i...\n2     {'login': 'jbrockmendel', 'id': 8078968, 'node...\n3     {'login': 'weikhor', 'id': 36619387, 'node_id'...\n4     {'login': 'weikhor', 'id': 36619387, 'node_id'...\n5     {'login': 'lukemanley', 'id': 8519523, 'node_i...\n6     {'login': 'milotoor', 'id': 4667801, 'node_id'...\n7     {'login': 'tehunter', 'id': 7980666, 'node_id'...\n8     {'login': 'jukiewiczm', 'id': 8179126, 'node_i...\n9     {'login': 'harahu', 'id': 6145801, 'node_id': ...\n10    {'login': 'dhern023', 'id': 7958975, 'node_id'...\n11    {'login': 'mroeschke', 'id': 10647082, 'node_i...\n12    {'login': 'jbrockmendel', 'id': 8078968, 'node...\n13    {'login': 'vnlitvinov', 'id': 45396231, 'node_...\n14    {'login': 'weikhor', 'id': 36619387, 'node_id'...\n15    {'login': 'timmy-ops', 'id': 89028359, 'node_i...\n16    {'login': 'topper-123', 'id': 26364415, 'node_...\n17    {'login': 'mvashishtha', 'id': 10712109, 'node...\n18    {'login': 'jbrockmendel', 'id': 8078968, 'node...\n19    {'login': 'mvashishtha', 'id': 10712109, 'node...\n20    {'login': 'McToel', 'id': 36071676, 'node_id':...\n21    {'login': 'timlod', 'id': 7346303, 'node_id': ...\n22    {'login': 'Sleepingwell', 'id': 294943, 'node_...\n23    {'login': 'smarie', 'id': 3236794, 'node_id': ...\n24    {'login': 'benjamrio', 'id': 12810626, 'node_i...\n25    {'login': 'alanhowells', 'id': 93594841, 'node...\n26    {'login': 'DriesSchaumont', 'id': 5946712, 'no...\n27    {'login': 'attack68', 'id': 24256554, 'node_id...\n28    {'login': 'jbrockmendel', 'id': 8078968, 'node...\n29    {'login': 'theOehrly', 'id': 23384863, 'node_i...\nName: user, dtype: object"

In [110]:
import requests

In [112]:
reqResponse = requests.get("https://api.github.com/repos/pandas-dev/pandas/issues")

In [127]:
d11 = reqResponse.json()

In [129]:
d11[0]['id']

1152726057

In [149]:
for i in range(len(d11)):
    print(d11[i]["id"],d11[i]['url'],d11[i]['repository_url'],d11[i]['comments_url'],sep="||")
    #print(d11[i]['user']['login'],d11[i]['user']['id'])

1152726057||https://api.github.com/repos/pandas-dev/pandas/issues/46165||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46165/comments
1152647346||https://api.github.com/repos/pandas-dev/pandas/issues/46164||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46164/comments
1152408767||https://api.github.com/repos/pandas-dev/pandas/issues/46163||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46163/comments
1151916356||https://api.github.com/repos/pandas-dev/pandas/issues/46162||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46162/comments
1151262706||https://api.github.com/repos/pandas-dev/pandas/issues/46161||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46161/comments
1150920527||https://api.github.com/repos/pandas-dev/pandas/issues/46156||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46156/comments
1150876170||https://api.github.com/repos/pandas-dev/pandas/issues/46154||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46154/comments
1150754239||https://api.github.com/repos/pandas-dev/pandas/issues/46152||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46152/comments
1150712051||https://api.github.com/repos/pandas-dev/pandas/issues/46149||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46149/comments
1150218652||https://api.github.com/repos/pandas-dev/pandas/issues/46147||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46147/comments
1150117069||https://api.github.com/repos/pandas-dev/pandas/issues/46145||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46145/comments
1150080362||https://api.github.com/repos/pandas-dev/pandas/issues/46144||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46144/comments
1149871773||https://api.github.com/repos/pandas-dev/pandas/issues/46142||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46142/comments
1149585395||https://api.github.com/repos/pandas-dev/pandas/issues/46141||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46141/comments
1149320791||https://api.github.com/repos/pandas-dev/pandas/issues/46140||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46140/comments
1149229930||https://api.github.com/repos/pandas-dev/pandas/issues/46138||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46138/comments
1148706907||https://api.github.com/repos/pandas-dev/pandas/issues/46137||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46137/comments
1148668016||https://api.github.com/repos/pandas-dev/pandas/issues/46135||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46135/comments
1148630898||https://api.github.com/repos/pandas-dev/pandas/issues/46133||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46133/comments
1148620065||https://api.github.com/repos/pandas-dev/pandas/issues/46132||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46132/comments
1148107383||https://api.github.com/repos/pandas-dev/pandas/issues/46129||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46129/comments
1147900564||https://api.github.com/repos/pandas-dev/pandas/issues/46126||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46126/comments
1147506497||https://api.github.com/repos/pandas-dev/pandas/issues/46122||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46122/comments
1147166642||https://api.github.com/repos/pandas-dev/pandas/issues/46116||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46116/comments
1146960626||https://api.github.com/repos/pandas-dev/pandas/issues/46114||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46114/comments
1146890381||https://api.github.com/repos/pandas-dev/pandas/issues/46112||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46112/comments
1146697595||https://api.github.com/repos/pandas-dev/pandas/issues/46111||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46111/comments
1146229238||https://api.github.com/repos/pandas-dev/pandas/issues/46105||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46105/comments
1146207257||https://api.github.com/repos/pandas-dev/pandas/issues/46104||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46104/comments
1146127800||https://api.github.com/repos/pandas-dev/pandas/issues/46101||https://api.github.com/repos/pandas-dev/pandas||https://api.github.com/repos/pandas-dev/pandas/issues/46101/comments

In [154]:
df22=pd.DataFrame(d11,columns=["id",'url','repository_url','comments_url','user'])

In [155]:
df22.to_csv("user_data.csv")